## Configuration: https://dependabot.com/docs/config-file/
## Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically
#
#version: 2
#
#updates:
#  - package-ecosystem: "pip"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    allow:
#      - dependency-type: "all"
#    commit-message:
#      prefix: ":arrow_up:"
#    open-pull-requests-limit: 1
#
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    allow:
#      - dependency-type: "all"
#    commit-message:
#      prefix: ":arrow_up:"
#    open-pull-requests-limit: 1
#
#  - package-ecosystem: "docker"
#    directory: "/docker"
#    schedule:
#      interval: "weekly"
#    allow:
#      - dependency-type: "all"
#    commit-message:
#      prefix: ":arrow_up:"
#    open-pull-requests-limit: 1
